// El catálogo de los cuadros del museo (#836): dos fichas y sus dos cartelas.
//
// POR QUÉ UN CATÁLOGO APARTE Y NO DOS ENTRADAS MÁS EN `museo-piezas.mjs`. No es
// orden: es que una estatua y un cuadro no se colocan igual. `CATALOGO_MUSEO`
// alimenta el reparto por PEDESTALES —fila, columna, cota de la coronilla— y
// meter ahí un cuadro le daría un pedestal en mitad de la sala. Un cuadro
// cuelga de un muro y su mirador mira al muro; son dos formas de colocar, y por
// eso son dos listas.
//
// LO QUE SÍ SE COMPARTE ES EL CONTRATO: estas fichas pasan por el MISMO
// `validarCatalogoPiezas` que las estatuas, con el mismo `naturaleza`
// obligatorio y la misma comprobación de que la `malla` referenciada existe de
// verdad. Lo único que cambia es contra qué registro se comprueba: allí son
// mallas de `data/mallas/`, aquí son composiciones de `museo-cuadro.mjs`. Dos
// validadores de licencia se desincronizan, y una licencia desincronizada no es
// un fallo de forma (#598).
//
// LA `naturaleza` ES `obra-propia`, Y ESA ES LA DECISIÓN QUE #836 TENÍA QUE
// TOMAR. La otra salida era colgar reproducciones de pintura real, y entonces
// ninguna de las cinco naturalezas servía: la fotografía de un óleo no es un
// escaneo, ni una fotogrametría, ni una reconstrucción. Habría hecho falta
// ampliar `NATURALEZAS`, traer los ficheros al árbol contra la regla de arte del
// módulo, y escribir procedencia real por cuadro. Pintarlos es lo que hace que
// no haya ninguna licencia ajena que gestionar — y de paso lo que permite decir
// en la cartela, sin rodeos, que lo que se mira lo generó una máquina.
//
// LA CARTELA DE UN CUADRO GENERADO TIENE QUE DECIR QUE LO ES. Es la misma norma
// de la casa que obliga al León a decir que es una reconstrucción y a la
// Afrodita a decir que es un vaciado: la sala no enseña nada sin decir qué es
// exactamente lo que se está enseñando. Una prueba lo comprueba en los dos
// idiomas, igual que con las estatuas.
//
// Puro: datos y nada más.

import { COMPOSICIONES } from "./museo-cuadro.mjs";

/** Los IDs de composición que existen. El registro contra el que valida el
 *  catálogo: una ficha que apunte a un dibujo que no está no llega a la sala. */
export const MALLAS_CUADROS = Object.freeze(Object.keys(COMPOSICIONES));

/** La procedencia es la misma para los dos, y es la más corta posible: no hay
 *  fuente externa. `original` es el `kind` que `procedencia-catalogo.mjs`
 *  reserva justo para esto, y por eso no lleva `source_url`: no hay ninguna
 *  página que consultar, el dibujo está en el árbol. */
const PROCEDENCIA_PROPIA = Object.freeze({
  kind: "original",
  source: "Espaciokoop Lagunak: pixelart generado por scripts/museo-cuadro.mjs",
  license: "GPL-2.0-or-later, como el resto del módulo",
});

export const CATALOGO_CUADROS = Object.freeze({
  formato: "espaciokoop-piezas",
  version: 1,
  piezas: Object.freeze([
    Object.freeze({
      id: "campo-partido",
      malla: "campo-partido",
      naturaleza: "obra-propia",
      nombre: Object.freeze({
        es: "Campo partido",
        en: "Divided field",
      }),
      cartela: Object.freeze({
        es: "No es una pintura: es una composición GENERADA por el propio"
          + " módulo, píxel a píxel, a dos centímetros y medio por píxel. No"
          + " reproduce ningún cuadro que exista ni pretende que lo parezca. Dos"
          + " masas de tierra que no se tocan y una línea de luz que no llega a"
          + " los bordes — si cruzara el lienzo entero sería un horizonte, y un"
          + " horizonte ya sería un sitio.",
        en: "This is not a painting: it is a composition GENERATED by the module"
          + " itself, pixel by pixel, at two and a half centimetres per pixel."
          + " It reproduces no existing work and does not pretend to. Two earth"
          + " masses that never meet and a line of light that stops short of the"
          + " edges — crossing the whole canvas it would be a horizon, and a"
          + " horizon would already be a place.",
      }),
      provenance: PROCEDENCIA_PROPIA,
    }),
    Object.freeze({
      id: "escalera-de-verdin",
      malla: "escalera-de-verdin",
      naturaleza: "obra-propia",
      nombre: Object.freeze({
        es: "Escalera de verdín",
        en: "Verdigris stair",
      }),
      cartela: Object.freeze({
        es: "También GENERADA por el módulo, y a propósito distinta de la de"
          + " enfrente: aquella es masa contra masa y esta es ritmo. Cuatro"
          + " bloques que suben, cada uno rematado en hueso. Lo que no es, y no"
          + " se puede leer como tal, es una medida: aquí no hay nada que"
          + " marque un nivel, una carga ni una distancia.",
        en: "Also GENERATED by the module, and deliberately unlike the one"
          + " across the room: that one is mass against mass, this one is"
          + " rhythm. Four rising blocks, each capped in bone white. What it is"
          + " not, and cannot be read as, is a measurement: nothing here marks a"
          + " level, a charge or a distance.",
      }),
      provenance: PROCEDENCIA_PROPIA,
    }),
  ]),
});
